esphome:
  name: geckocontrol
  platform: ESP32
  board: nodemcu-32s
  includes: gecko_custom.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Geckocontrol Fallback Hotspot"
    password: !secret fallback_password

#captive_portal:

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:

custom_component:
- lambda: |-
    auto gecko_custom = new GeckoCustomComponent();
    return {gecko_custom};

switch:
  - platform: gpio
    name: "Heat Lamp"
    pin: 15
    id: heat_lamp
  - platform: template
    id: fan_switch
    name: "Ventilator on/off"
    on_turn_on:
      then:
        - output.set_level:
            id: fan_pwm
            level: 75%
    on_turn_off:
      then:
        - output.set_level:
            id: fan_pwm
            level: 0%

  - platform: template
    id: pump_switch_momentary
    name: "Let it rain"
    turn_on_action:
      - output.turn_on:
          id: rain_pump
      - delay: 5s
      - output.turn_off:
          id: rain_pump
      - switch.turn_off: pump_switch_momentary

  - platform: template
    name: "PID Climate Autotune"
    turn_on_action:
      - climate.pid.autotune: pid_humidity

output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: 16
    min_power: 15%
    zero_cross_pin:
      number: 17
      mode: INPUT
      inverted: no
  - platform: slow_pwm
    pin: 2
    id: heat_bed_pwm
    period: 2min
  - platform: gpio
    pin: 4
    id: rain_pump
  - platform: ledc
    pin: 32
    id: component_red
  - platform: ledc
    pin: 33
    id: component_green
  - platform: ledc
    pin: 27
    id: component_blue
  - platform: ledc
    pin: GPIO14
    id: fan_pwm
    frequency: 25000 hz
    channel: 4
  - platform: custom
    type: float
    lambda: |-
      auto rain_pump_output_c = new RainPumpOutput();
      App.register_component(rain_pump_output_c);
      return {rain_pump_output_c};
    outputs:
      id: rain_pump_float
      #period: 30min
      max_power: 0.01
      # max. 18 seconds of rain per half hour

light:
  - platform: monochromatic
    id: day_light
    output: dimmer1
    name: "Dimmer Daylight"
    gamma_correct: 1.0
    default_transition_length: 0s

  - platform: rgb
    name: "Scenic Light"
    id: scenic_light
    red: component_red
    green: component_green
    blue: component_blue
    effects:
      - lambda:
          name: Lightning
          update_interval: 50ms
          lambda: |-
            static bool flashing = true;
            static uint8_t r = 0;
            auto call = id(scenic_light).make_call();
            if (r == 0) {
              call.set_rgb(1.,1.,1.);
              call.perform();
            }
            r = random(1,100);
            if (r > 95) {
              call.set_transition_length(5);
              call.set_brightness(1.0);
              call.perform();
              flashing = true;
            } else if (flashing) {
              call.set_transition_length(300);
              call.set_brightness(0.01);
              call.perform();
              flashing = false;
            }

  - platform: monochromatic
    output: fan_pwm
    name: "Ventilator"
    gamma_correct: 1.0

i2c:
  sda: 25
  scl: 26
  scan: True
  id: bus_a

dallas:
  - pin: 22
    update_interval: 5min

sensor:
  - platform: hx711
    name: "Scale"
    dout_pin: 34
    clk_pin: 13
    gain: 128
    update_interval: 60s
    unit_of_measurement: g
    filters:
      - calibrate_linear:
          - -29500 -> 0
          - -118200 -> 42.5

  - platform: dallas
    address: !secret DsAddressHeatBed
    name: "Temperature HeatBed"
    unit_of_measurement: "°C"
    id: temperature_heatbed

  - platform: dallas
    address: !secret DsAddressSubstrate
    name: "Temperature Substrate"
    unit_of_measurement: "°C"
    id: temperature_substrate

  - platform: bme280
    temperature:
      name: "Air Temperature"
      oversampling: 16x
      id: temperature_air
    pressure:
      name: "Air Pressure"
    humidity:
      name: "Air Humidity"
      id: humidity
    address: 0x76
    update_interval: 60s

  - platform: pulse_counter
    name: "Fan Tacho"
    pin: 35
    unit_of_measurement: rpm
    update_interval: 60s
    filters:
      multiply: 0.5

  - platform: sun
    name: Sun Elevation
    type: elevation

  - platform: homeassistant   # Forecast minimal temperature
    id: weather_tempmin
    entity_id: sensor.today_min
    on_value:
      then:
        - climate.control:
              id: thermostat_air
              target_temperature_low: !lambda |-
                return x;

  - platform: homeassistant   # Forecast maximal temperature
    id: weather_tempmax
    entity_id: sensor.today_max
    on_value:
      then:
        - climate.control:
              id: thermostat_air
              target_temperature_high: !lambda |-
                return x;
        #- climate.control:
              #id: pid_heatbed
              #target_temperature: !lambda |-
                #return x+5.;
  - platform: homeassistant   # Forecast precipitation
    id: weather_precipitation
    entity_id: sensor.today_rain

sun:
  latitude: -22.6
  longitude: 167.5

# Sunset and Sunrise flipped because we are on the other side of the globe
  on_sunset:
    - elevation: 0°
      then:
        - lambda: |-
              auto call = id(scenic_light).turn_on();
              call.set_effect("Sunrise Color");
              call.perform();
              auto call2 = id(day_light).turn_on();
              call2.set_effect("Sunrise Daylight");
              call2.perform();
        - logger.log: Good morning, Gecko.

  on_sunrise:
    - elevation: -60°
      then:
        - lambda: |-
              auto call = id(day_light).make_call();
              call.set_effect("Sunset Daylight");
              call.perform();
    - elevation: -6°
      then:
        - logger.log: Good night, Gecko.
        - lambda: |-
              auto call = id(scenic_light).turn_on();
              call.set_effect("Sunset Color");
              call.perform();

time:
  - platform: homeassistant
    id: esptime

climate:
  - platform: thermostat
    id: thermostat_air
    name: "Thermostat Air Temp"
    sensor: temperature_air
    default_target_temperature_low: 20 °C
    default_target_temperature_high: 28 °C
    cool_action:
      - switch.turn_on: fan_switch
    heat_action:
      - switch.turn_on: heat_lamp
    idle_action:
      - switch.turn_off: heat_lamp
      - switch.turn_off: fan_switch

  #- platform: pid
    #id: pid_heatbed
    #name: "PID Heatbed"
    #sensor: temperature_heatbed
    #default_target_temperature: 30°C
    #heat_output: heat_bed_pwm
    #control_parameters:
      #kp: 2.5
      #ki: 0.5
      #kd: 1.0

  - platform: pid
    id: pid_humidity 
    name: "Humidity"
    sensor: humidity
    default_target_temperature: 65
    heat_output: rain_pump_float
    control_parameters:
      kp: 0.0
      ki: 0.0
      kd: 0.0
    visual:
      min_temperature: 30
      max_temperature: 98
      temperature_step: 2

globals:
   - id: scenic_light_effect
     type: uint8_t
     restore_value: no
     initial_value: '0'

status_led:
  pin: GPIO12
