esphome:
  name: geckocontrol
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Geckocontrol Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:

switch:
  - platform: gpio
    name: "Pump"
    pin: 4

  - platform: gpio
    name: "HeatBed"
    pin: 2

  - platform: gpio
    name: "HeatLamp"
    pin: 15

output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: 16
    min_power: 15%
    zero_cross_pin:
      number: 17
      mode: INPUT
      inverted: no
  - platform: ledc
    pin: 32
    id: component_red
  - platform: ledc
    pin: 33
    id: component_green
  - platform: ledc
    pin: 27
    id: component_blue
  - platform: ledc
    pin: GPIO14
    id: fan_pwm
    frequency: 25000 hz
    channel: 4

light:
  - platform: monochromatic
    output: dimmer1
    name: "Dimmer Daylight"
    gamma_correct: 1.0
    default_transition_length: 0s

  - platform: rgb
    name: "Scenic Light"
    red: component_red
    green: component_green
    blue: component_blue

  - platform: monochromatic
    output: fan_pwm
    name: "Ventilator"
    gamma_correct: 1.0

i2c:
  sda: 25
  scl: 26
  scan: True
  id: bus_a

dallas:
  - pin: 22

sensor:
  - platform: hx711
    name: "Scale"
    dout_pin: 34
    clk_pin: 13
    gain: 128
    update_interval: 60s
    unit_of_measurement: g
    filters:
      - calibrate_linear:
          - -29500 -> 0
          - -118200 -> 42.5

  - platform: dallas
    address: 0x0305473B405A0028
    name: "Temperature HeatBed"
    unit_of_measurement: "°C"

  - platform: dallas
    address: 0x5505473B82670028
    name: "Temperature Substrate"
    unit_of_measurement: "°C"

  - platform: bme280
    temperature:
      name: "Air Temperature"
      oversampling: 16x
    pressure:
      name: "Air Pressure"
    humidity:
      name: "Air Humidity"
    address: 0x76
    update_interval: 60s

  - platform: pulse_counter
    name: "Fan Tacho"
    pin: 35
    unit_of_measurement: rpm
    update_interval: 60s
    filters:
      multiply: 0.5
