esphome:
  name: geckonewcomponent
  platform: ESP32
  board: nodemcu-32s
  includes:
    - ".esphome/build/geckocontrol/src/esphome/core/log.h"

external_components:
  - source:
      type: local
      path: custom_components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Geckocontrol Fallback Hotspot"
    password: !secret fallback_password

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:

      then:
        - lambda: |-
            ESP_LOGD("skycond_attenuation", "set_action: %.2f", x);

  - platform: template
    name: "randomness"
    id: random_sensor
    update_interval: 10s
    state_class: "measurement"
    accuracy_decimals: 2
    lambda: |-
      return (rand() % 100) / 100.f;
sensor:

terralight:
  id: terrariumlight
  name: "Terrarium Light Controller"
  entity_id: sensor.sky_in_france_noumea_182_days_ago

light:
  - platform: monochromatic
    id: day_light
    output: dimmer1
    name: "Dimmer Daylight"
    gamma_correct: 1.0
    default_transition_length: 0s

  - platform: rgb
    name: "Scenic Light"
    id: scenic_light
    red: component_red
    green: component_green
    blue: component_blue

output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: 16
    min_power: 15%
    zero_cross_pin:
      number: 17
      mode: INPUT
      inverted: no
  - platform: ledc
    pin: 32
    id: component_red
    channel: 0
  - platform: ledc
    pin: 33
    id: component_green
    channel: 2
  - platform: ledc
    pin: 27
    id: component_blue
    channel: 4
  - platform: template
    id: daylight_attenuation_output
    type: float
    write_action:
      - lambda: |-
          id(twilight_attenuation) = state;
          ESP_LOGD("gecko-newcomponent", "wrote twilight_attenuation: %.2f", id(twilight_attenuation));

climate:
  - platform: pid
    id: hygrostat
    name: "Hygrostat"
globals:
   - id: scenic_light_effect
     type: uint8_t
     restore_value: no
     initial_value: '0'

   - id: skycond_attenuation
     type: float
     restore_value: no
     initial_value: '0.7'

   - id: twilight_attenuation
     type: float
     restore_value: no
     initial_value: '1'
