esphome:
  name: geckocontrol
  platform: ESP32
  board: nodemcu-32s
  includes:
    - gecko_custom.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Geckocontrol Fallback Hotspot"
    password: !secret fallback_password

#captive_portal:

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  services:
    - service: control_rain
      variables:
        level: float
      then:
        - output.set_level:
            id: rain_pump_float
            level: !lambda 'return level / 100.0;'
ota:

custom_component:
- lambda: |-
    auto gecko_custom = new GeckoCustomComponent();
    return {gecko_custom};

switch:
  - platform: template
    id: heat_lamp
    name: "Heat Lamp on/off"
    turn_on_action:
      then:
        - output.set_level:
            id: heat_lamp_pwm
            level: 100%
    turn_off_action:
      then:
        - output.set_level:
            id: heat_lamp_pwm
            level: 0%

  - platform: template
    id: pump_switch_momentary
    name: "Let it rain"
    turn_on_action:
      - output.turn_on:
          id: rain_pump
      - delay: 5s
      - output.turn_off:
          id: rain_pump
      - switch.turn_off: pump_switch_momentary

  - platform: template
    id: fog_switch_momentary
    name: "Sleepy hollow"
    turn_on_action:
      - output.set_level:
            id: fogger_float
            level: 100%
      - delay: 30s
      - output.set_level:
            id: fogger_float
            level: 0%
      - switch.turn_off: fog_switch_momentary

  - platform: template
    name: "PID Humidity Autotune"
    turn_on_action:
      - climate.pid.autotune: humidity_control

output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: 16
    min_power: 15%
    zero_cross_pin:
      number: 17
      mode: INPUT
      inverted: no
  - platform: slow_pwm
    pin: 15
    id: heat_lamp_pwm
    period: 2min
  - platform: gpio
    pin: 4
    id: rain_pump
  - platform: slow_pwm
    pin: 2
    id: fogger_float
    min_power: 0.0
    max_power: 0.25
    period: 120s
  - platform: ledc
    pin: 32
    id: component_red
  - platform: ledc
    pin: 33
    id: component_green
  - platform: ledc
    pin: 27
    id: component_blue
  - platform: ledc
    pin: GPIO14
    id: fan_pwm
    frequency: 25000 hz
    channel: 4
  - platform: custom
    type: float
    lambda: |-
      auto rain_pump_output_c = new RainPumpOutput();
      App.register_component(rain_pump_output_c);
      return {rain_pump_output_c};
    outputs:
      id: rain_pump_float
      #period: 30min
      max_power: 0.02
      # max. 18 seconds of rain per half hour
  - platform: template
    id: fan_dehumidifier
    type: float
    write_action:
      # fan slider MUST be controlled with FanStateCalls, fan->turn_on() etc. don't work
      - lambda: |-
            ClimateAction action = id(humidity_control).action;
            if (action == CLIMATE_ACTION_COOLING || action == CLIMATE_ACTION_DRYING) {
              auto fan = id(fan_speed).make_call();
              ESP_LOGD(TAG, "Active Humidity PID Controller set fan to: %f ", state);
              if (state) {
                fan.set_state(true);
                fan.set_speed(state*100);
              } else {
                fan.set_state(false);
              }
              fan.perform();
            } else {
              ESP_LOGD(TAG, "Humidity PID Controller not currently drying, ignore fan value of %f", state);
            }

  - platform: template
    id: fan_cooler
    type: binary
    write_action:
      - lambda: |-
            ClimateAction action = id(humidity_control).action;
            if (state && action == CLIMATE_ACTION_HEATING) {
              ESP_LOGD(TAG, "not turning on cooling fan because currently humidifying!");
            } else {
              ESP_LOGD(TAG, "Temperature PID Controller set fan to: %d ", state);
              auto fan = id(fan_speed).make_call();
              fan.set_state(state);
              fan.perform();
            }


light:
  - platform: monochromatic
    id: day_light
    output: dimmer1
    name: "Dimmer Daylight"
    gamma_correct: 1.0
    default_transition_length: 0s

  - platform: rgb
    name: "Scenic Light"
    id: scenic_light
    red: component_red
    green: component_green
    blue: component_blue
    effects:
      - lambda:
          name: Lightning
          update_interval: 50ms
          lambda: |-
            static bool flashing = true;
            static uint8_t r = 0;
            auto call = id(scenic_light).make_call();
            if (r == 0) {
              call.set_rgb(1.,1.,1.);
              call.perform();
            }
            r = random(1,100);
            if (r > 95) {
              call.set_transition_length(5);
              call.set_brightness(1.0);
              call.perform();
              flashing = true;
            } else if (flashing) {
              call.set_transition_length(300);
              call.set_brightness(0.01);
              call.perform();
              flashing = false;
            }

fan:
  - platform: speed
    id: fan_speed
    output: fan_pwm
    name: "Ventilation"
    speed_count: 100

i2c:
  sda: 25
  scl: 26
  scan: True
  id: bus_a

dallas:
  - pin: 22
    update_interval: 5min

sensor:
  - platform: hx711
    name: "Scale"
    dout_pin: 34
    clk_pin: 13
    gain: 128
    update_interval: 15s
    accuracy_decimals: 2
    unit_of_measurement: g
    filters:
      - calibrate_linear:
          - 250000 -> 0
          - 456666 -> 100
      - delta: 0.2
      - filter_out: -121
      - lambda: |-
            return (x > 2.5 ? x : 0.0);

  - platform: dallas
    address: !secret DsAddressHeatBed
    name: "Temperature HeatBed"
    unit_of_measurement: "°C"
    id: temperature_heatbed

  - platform: dallas
    address: !secret DsAddressSubstrate
    name: "Temperature Substrate"
    unit_of_measurement: "°C"
    id: temperature_substrate

  - platform: bme280
    temperature:
      name: "Ceiling Temperature"
      oversampling: 16x
      id: temperature_ceiling
      filters:
        - lambda: |-
            if (x > 0 && x < 60)
              return x;
            return {};
    pressure:
      name: "Air Pressure"
    humidity:
      name: "Ceiling Humidity"
      id: humidity_ceiling
      filters:
        - filter_out: 100
        - filter_out: 0
    address: 0x76
    update_interval: 15s

  - platform: sht3xd
    temperature:
      name: "Ground Temperature"
      id: temperature_ground
      filters:
        - lambda: |-
            if (x > 0 && x < 60)
              return x;
            return {};
    humidity:
      name: "Ground Humidity"
      id: humidity_ground
    address: 0x44
    update_interval: 20s

  - platform: pulse_counter
    name: "Fan Tacho"
    pin: 35
    unit_of_measurement: rpm
    update_interval: 60s
    filters:
      multiply: 0.5

  - platform: sun
    name: Sun Elevation
    type: elevation

  - platform: homeassistant   # actual historic temperature
    id: weather_temperature
    entity_id: sensor.temperature_noumea
    on_value:
      then:
        - climate.control:
              id: thermostat_air
              target_temperature_low: !lambda |-
                return x-2;
              target_temperature_high: !lambda |-
                return x+2;

  - platform: homeassistant   # actual historic humidity
    id: weather_humidity
    entity_id: sensor.humidity_noumea
    on_value:
      then:
        - climate.control:
              id: humidity_control
              target_temperature: !lambda |-
                return x-1;

  - platform: homeassistant   # actual historic rain intensity (range 0-5)
    id: weather_precipitation
    entity_id: sensor.rain_noumea
    on_value:
      then:
        - output.set_level:
            id: rain_pump_float
            level: !lambda |-
                return x/5.0;

  # actual historic sky conditions
  # a numeric value in the range of (0-22) which indicates increasing sky covering
  # we're going to interpret it as a correction factor for the daylight intensitiy,
  # the higher the value, the more daylight will be dimmed down
  - platform: homeassistant
    id: weather_sky
    entity_id: sensor.sky_noumea
    on_value:
      then:
        - lambda: |-
            ESP_LOGD(TAG, "sky value changed to: %f ", x);
            float b, dim_factor;
            id(day_light).current_values_as_brightness(&b);
            ESP_LOGD(TAG, "previous attenuated brightness: %f", b);
            b /= id(daylight_attenuation);
            ESP_LOGD(TAG, "previous normalized brightness: %f", b);
            id(daylight_attenuation) = id(daylight_max) * (24-x)/24;
            b *= id(daylight_attenuation);
            ESP_LOGD(TAG, "daylight_attenuation: %f", id(daylight_attenuation));
            ESP_LOGD(TAG, "target_brightness: %f", b);
            auto call = id(day_light).make_call();
            call.set_transition_length(60*1000);
            call.set_brightness(b);
            call.perform();

  - platform: template
    name: "Combined humidity"
    id: humidity_combined
    update_interval: 15s
    unit_of_measurement: "%"
    device_class: "humidity"
    state_class: "measurement"
    accuracy_decimals: 1
    lambda: |-
      return (id(humidity_ceiling).state + id(humidity_ground).state) / 2.0;

time:
  - platform: homeassistant
    id: esptime
    on_time_sync:
      then:
        - lambda: |-
              auto ts = id(esptime).now();
              ESPTime remote_ts = time::ESPTime::from_epoch_utc(ts.timestamp - 182*24*60*60);
              char datetimestr[21];
              remote_ts.strftime(datetimestr, 20, "%Y-%m-%d %H:%M:%S");
              ESP_LOGD(TAG, "offset timestamp: %s", datetimestr);
              id(remote_time).set_epoch_time(ts.timestamp - 182*24*60*60);

  - platform: homeassistant
    id: remote_time
    timezone: Pacific/Noumea
    on_time_sync:
      then:
        - logger.log: "Synchronized remote_time"
        - lambda: |-
              auto ts = id(remote_time).now();
              ESPTime remote_ts = time::ESPTime::from_epoch_utc(ts.timestamp);
              char datetimestr[21];
              remote_ts.strftime(datetimestr, 20, "%Y-%m-%d %H:%M:%S");
              ESP_LOGD(TAG, "remote_time timestamp = %s", datetimestr);

sun:
  id: remote_sun
  time_id: remote_time
  #latitude: -22.6
  #longitude: 167.5
  # Take original Noumea / Nouvelle-Calédonie latitude
  # but mirror it to the northern hemisphere
  # and use actual local longitude
  latitude: 22.6
  longitude: 9.15

  on_sunrise:
    - elevation: 20°
      then:
        - lambda: |-
              auto call = id(scenic_light).turn_on();
              call.set_effect("Sunrise Color");
              call.perform();
              auto call2 = id(day_light).turn_on();
              call2.set_effect("Sunrise Daylight");
              call2.perform();
        - logger.log: Good morning, Gecko.

  on_sunset:
    - elevation: 44°
      then:
        - lambda: |-
              auto call = id(day_light).make_call();
              call.set_effect("Sunset Daylight");
              call.perform();
    - elevation: 5°
      then:
        - logger.log: Good night, Gecko.
        - lambda: |-
              auto call = id(scenic_light).turn_on();
              call.set_effect("Sunset Color");
              call.perform();

climate:
  - platform: thermostat
    id: thermostat_air
    name: "Thermostat Air Temp"
    sensor: temperature_ceiling
    default_target_temperature_low: 20 °C
    default_target_temperature_high: 28 °C
    min_cooling_off_time: 60s
    min_cooling_run_time: 60s
    min_heating_off_time: 60s
    min_heating_run_time: 120s
    min_idle_time: 60s
    cool_action:
      - output.turn_on: fan_cooler
    heat_action:
      - switch.turn_on: heat_lamp
    idle_action:
      - switch.turn_off: heat_lamp
      - output.turn_off: fan_cooler

  - platform: pid
    id: humidity_control
    name: "Humidity"
    sensor: humidity_combined
    default_target_temperature: 70 °C
    heat_output: fogger_float
    cool_output: fan_dehumidifier
    visual:
      min_temperature: 30
      max_temperature: 100
      temperature_step: 2
    control_parameters:
      kp: 0.22
      ki: 0.005
      kd: 6.38

globals:
   - id: scenic_light_effect
     type: uint8_t
     restore_value: no
     initial_value: '0'

   - id: daylight_max
     type: float
     restore_value: no
     initial_value: '0.75'

   - id: daylight_attenuation
     type: float
     restore_value: no
     initial_value: '0.7'

status_led:
  pin: GPIO12
