esphome:
  name: geckocontrolnewcomponent
  platform: ESP32
  board: nodemcu-32s
  # includes:
  #   - gecko_custom.h

external_components:
  - source:
      type: local
      path: custom_components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Geckocontrol Fallback Hotspot"
    password: !secret fallback_password

#captive_portal:

# Enable logging
logger:
  level: DEBUG

# custom_component:
# - lambda: |-
#     auto gecko_custom = new GeckoCustomComponent();
#     return {gecko_custom};
#   components:
#     - id: gecko

fan:
  - platform: multi
    id: gecko_multifan
    output: fan_pwm

output:
  - platform: ledc
    pin: GPIO14
    id: fan_pwm
    frequency: 25000 hz
    channel: 7

memory:
