esphome:
  name: geckocontrol
  platform: ESP32
  board: nodemcu-32s
  includes: gecko_custom.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Geckocontrol Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:

switch:
  - platform: gpio
    name: "Heat Lamp"
    pin: 15
    id: heat_lamp
  - platform: template
    id: fan_switch
    name: "Ventilator on/off"
    on_turn_on:
      then:
        - output.set_level:
            id: fan_pwm
            level: 75%
    on_turn_off:
      then:
        - output.set_level:
            id: fan_pwm
            level: 0%

  - platform: template
    id: pump_switch_momentary
    name: "Let it rain"
    turn_on_action:
      - output.set_level:
          id: rain_pump
          level: 100%
      - delay: 5s
      - output.set_level:
          id: rain_pump
          level: 0%
      - switch.turn_off: pump_switch_momentary

# doesn't work - can't be switched off manually
  - platform: template
    id: heat_bed_manual
    name: "Manually heat bed"
    turn_on_action:
      - output.set_level:
          id: heat_bed_pwm
          level: 100%
    turn_off_action:
      - switch.turn_off: heat_bed_internal
      - output.set_level:
          id: heat_bed_pwm
          level: 0%
  - platform: gpio
    name: "Heat Bed"
    id: heat_bed_internal
    pin: 2

output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: 16
    min_power: 15%
    zero_cross_pin:
      number: 17
      mode: INPUT
      inverted: no
  - platform: slow_pwm
    pin: 2
    id: heat_bed_pwm
    period: 2min
  - platform: slow_pwm
    pin: 4
    id: rain_pump
    period: 60min
    max_power: 0.05
    # max. 3 min of contiuous rain per hour
  - platform: ledc
    pin: 32
    id: component_red
  - platform: ledc
    pin: 33
    id: component_green
  - platform: ledc
    pin: 27
    id: component_blue
  - platform: ledc
    pin: GPIO14
    id: fan_pwm
    frequency: 25000 hz
    channel: 4

light:
  - platform: monochromatic
    output: dimmer1
    name: "Dimmer Daylight"
    gamma_correct: 1.0
    default_transition_length: 0s

  - platform: rgb
    name: "Scenic Light"
    id: scenic_light
    red: component_red
    green: component_green
    blue: component_blue
    effects:
      - lambda:
          name: Lightning
          update_interval: 50ms
          lambda: |-
            static bool flashing = true;
            static uint8_t r = 0;
            auto call = id(scenic_light).make_call();
            if (r == 0) {
              call.set_rgb(1.,1.,1.);
              call.perform();
            }
            r = random(1,100);
            if (r > 95) {
              call.set_transition_length(5);
              call.set_brightness(1.0);
              call.perform();
              flashing = true;
            } else if (flashing) {
              call.set_transition_length(300);
              call.set_brightness(0.01);
              call.perform();
              flashing = false;
            }
      - lambda:
          name: Sunrise
          update_interval: 1s
          lambda: |-
            static uint8_t i = 0;
            static uint16_t skip = 0;
            static uint16_t delay = id(sun_effect_delay);
            if (++skip < delay)
              return;
            auto call = id(scenic_light).make_call();
            if (i < SUN_LUT_LEN)
            {
              call.set_transition_length(1000*delay);
              float a, r, g, b;
              a = sun_lut[i][0] / 255.;
              r = sun_lut[i][1] / 255.;
              g = sun_lut[i][2] / 255.;
              b = sun_lut[i][3] / 255.;
              call.set_brightness(a);
              call.set_rgb(r,g,b);
              i++;
            } else {
              i = 0;
              call.set_effect(0);
            }
            call.perform();
            skip = 0;
      - lambda:
          name: Sunset
          update_interval: 1s
          lambda: |-
            static int8_t i = SUN_LUT_LEN-1;
            static uint16_t skip = 0;
            static uint16_t delay = id(sun_effect_delay);
            if (++skip < delay)
              return;
            auto call = id(scenic_light).make_call();
            if (i > 0)
            {
              call.set_transition_length(1000*delay);
              float a, r, g, b;
              a = sun_lut[i][0] / 255.;
              r = sun_lut[i][1] / 255.;
              g = sun_lut[i][2] / 255.;
              b = sun_lut[i][3] / 255.;
              call.set_brightness(a);
              call.set_rgb(r,g,b);
              i--;
            } else {
              i = SUN_LUT_LEN-1;
              call.set_effect(0);
            }
            call.perform();
            skip = 0;
      - random:
          name: Random Effect With Custom Values
          transition_length: 5s
          update_interval: 7s

  - platform: monochromatic
    output: fan_pwm
    name: "Ventilator"
    gamma_correct: 1.0

i2c:
  sda: 25
  scl: 26
  scan: True
  id: bus_a

dallas:
  - pin: 22

sensor:
  - platform: hx711
    name: "Scale"
    dout_pin: 34
    clk_pin: 13
    gain: 128
    update_interval: 60s
    unit_of_measurement: g
    filters:
      - calibrate_linear:
          - -29500 -> 0
          - -118200 -> 42.5

  - platform: dallas
    address: 0x0305473B405A0028
    name: "Temperature HeatBed"
    unit_of_measurement: "°C"
    id: temperature_heatbed

  - platform: dallas
    address: 0x5505473B82670028
    name: "Temperature Substrate"
    unit_of_measurement: "°C"
    id: temperature_substrate

  - platform: bme280
    temperature:
      name: "Air Temperature"
      oversampling: 16x
      id: temperature_air
    pressure:
      name: "Air Pressure"
    humidity:
      name: "Air Humidity"
      id: humidity
    address: 0x76
    update_interval: 60s

  - platform: pulse_counter
    name: "Fan Tacho"
    pin: 35
    unit_of_measurement: rpm
    update_interval: 60s
    filters:
      multiply: 0.5

sun:
  latitude: -22.6
  longitude: 167.5

time:
  - platform: homeassistant

climate:
  - platform: thermostat
    name: "Thermostat Air Temp"
    sensor: temperature_air
    default_target_temperature_low: 20 °C
    default_target_temperature_high: 28 °C
    cool_action:
      - switch.turn_on: fan_switch
    heat_action:
      - switch.turn_on: heat_lamp
    idle_action:
      - switch.turn_off: heat_lamp
      - switch.turn_off: fan_switch

  - platform: pid
    id: pid_headbed
    name: "PID Heatbed"
    sensor: temperature_heatbed
    default_target_temperature: 30°C
    heat_output: heat_bed_pwm
    control_parameters:
      kp: 2.5
      ki: 0.5
      kd: 1.0

  - platform: pid
    id: pid_humidity
    name: "Humidity"
    sensor: humidity
    default_target_temperature: 75
    heat_output: rain_pump
    control_parameters:
      kp: 0.5
      ki: 0.1
      kd: 0.05

globals:
   - id: scenic_light_effect
     type: uint8_t
     restore_value: no
     initial_value: '0'
   - id: sun_effect_delay
     type: uint16_t
     restore_value: no
     initial_value: '5'

binary_sensor:
  - platform: template
    name: "effects"
    on_click:
    - lambda: |-
              auto call = id(scenic_light).turn_on();

              if (id(scenic_light_effect) == 0)
                  call.set_effect("random");

              if (id(scenic_light_effect) == 1)
                  call.set_effect("lambda");

              if (id(scenic_light_effect) == 2)
                  call.set_effect("lambda");

              if (id(scenic_light_effect) < 3)
                  id(scenic_light_effect) = 0;
              else
                  id(scenic_light_effect) += 1;

              call.perform();

